internal_sources:
  - name: my
    repo: null
    path: ./sops/my

external_sources:
  - name: general-search
    engine: gemini
    api_key: ${GEMINI_API_KEY}
    urls:  # optional URLs for this engine
      - "https://en.wikipedia.org/wiki/Python_(programming_language)"
      - "https://stackoverflow.com/questions/tagged/python"

  - name: aws-docs
    engine: gemini
    api_key: ${GEMINI_API_KEY}
    urls:
      - "https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/CacheNodes.Memory.html"
      - "https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/troubleshooting-high-memory-usage.html"
